# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AZURE_KEYVAULT_EMULATOR_CERTIFICATE_DIRECTORY: '/tmp/kvemulator'
      

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install SSL Certificates
      run: |
        dotnet dev-certs https --trust
        echo Creating .crt and .pfx to be used in emulator container

        cd '/tmp/'

        mkdir 'kvemulator'

        cd 'kvemulator'
        
        dotnet dev-certs https -ep ./emulator.crt  -q
        
        echo Created emulator.crt with password emulator
        
        dotnet dev-certs https -ep ./emulator.pfx  -q
        
        echo Created emulator.pfx with password emulator. You must now install these certificates locally as a Trusted Root CA Authority.
        cp emulator.crt /usr/local/share/ca-certificates/emulator.crt && update-ca-certificates
    - name: Test
      run: dotnet test --no-build --verbosity normal
